# Generated by Django 4.2.6 on 2024-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('reservada', 'Esta mesa já está reservada'), ('não reservada', 'Esta mesa ainda não está reservada')], max_length=128)),
            ],
        ),
    ]
