# Generated by Django 4.2.6 on 2024-05-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('mesa', '0001_initial'),
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparo', 'Em preparo'), ('finalizado', 'Finalizado')], max_length=128)),
                ('comanda', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comanda.comanda')),
                ('itens', models.ManyToManyField(to='item.item')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.mesa')),
            ],
        ),
    ]
